export default [
    {
        "name": "Healing Vial",
        "type": "Health Bonus",
        "category": "Healing",
        "effect": "Restores 1 health. Can overcharge up to +100.",
        "notes": "",
        "carriable": false,
        // "description": "A small flask of mysterious blue liquid. Rapidly dissipates into the body when ingested and heals damaged cells.",
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Strong Healing Vial",
        "type": "Health Bonus",
        "category": "Healing",
        "effect": "Restores 3 health. Can overcharge up to +100.",
        "notes": "",
        "carriable": false,
        // "description": "A small flask of mysterious green liquid. Has a more potent healing factor than the blue variety.",
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Greater Healing Vial",
        "type": "Health Bonus",
        "category": "Healing",
        "effect": "Restores 6 health. Can overcharge up to +200.",
        "notes": "",
        "carriable": false,
        // "description": "A small flask of mysterious yellow liquid. ",
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Minor Vitality Booster",
        "type": "Health Bonus",
        "category": "Healing",
        "effect": "Restores 10 health. Can overcharge up to +200. Increases max health by 1, up to a total of 50.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 1
    },
    {
        "name": "Major Vitality Booster",
        "type": "Health Bonus",
        "category": "Healing",
        "effect": "Restores 15 health. Can overcharge up to +200. Increases max health by 3, up to a total 50.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 1
    },
    {
        "name": "Armor Shard",
        "type": "Armor Bonus",
        "category": "Healing",
        "effect": "Restores 1 armor. Can overcharge up to +100.",
        "notes": "Provides 20% protection if applied without armor.",
        "carriable": false,
        // "description": "A small slab of metal that can be used to patch up damaged armor. Provides very little protection on its own.",
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Strong Armor Shard",
        "type": "Armor Bonus",
        "category": "Healing",
        "effect": "Restores 3 armor. Can overcharge up to +100.",
        "notes": "Provides 20% protection if applied without armor.",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Greater Armor Shard",
        "type": "Armor Bonus",
        "category": "Healing",
        "effect": "Restores 6 armor. Can overcharge up to +200.",
        "notes": "Provides 20% protection if applied without armor.",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },

    {
        "name": "Stimpack",
        "type": "Small Health Pack",
        "category": "Healing",
        "effect": "Restores 10 health.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Stabilizing Syringe",
        "type": "Small Health Pack",
        "category": "Healing",
        "effect": "Restores 10 health and clears all negative status effects.",
        "notes": "",
        "carriable": true,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Medikit",
        "type": "Large Health Pack",
        "category": "Healing",
        "effect": "Restores 25 health.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Field Kit",
        "type": "Large Health Pack",
        "category": "Healing",
        "effect": "Restores 25 health.",
        "notes": "",
        "carriable": true,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Trauma Kit",
        "type": "Large Health Pack",
        "category": "Healing",
        "effect": "Restores 40 health.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Berserk Pack",
        "type": "Booster Pack",
        "category": "Healing",
        "effect": "Restores 100 health and grants Berserk for the rest of the level.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },

    {
        "name": "Soul Sphere",
        "type": "Supercharge",
        "category": "Healing",
        "effect": "Restores 100 health. Can overcharge up to +100.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Life Sphere",
        "type": "Supercharge",
        "category": "Healing",
        "effect": "Restores 150 health. Can overcharge up to +200.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Overcharge Sphere",
        "type": "Supercharge",
        "category": "Healing",
        "effect": "Restores 200 health. Can overcharge up to +200.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Salvation Sphere",
        "type": "Supercharge",
        "category": "Healing",
        "effect": "Saves you from death once. Grants 100 health and a few seconds of invincibility after use.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Mega Sphere",
        "type": "Megacharge",
        "category": "Healing",
        "effect": "Fully restores health and armor and overcharges both by +100.",
        "notes": "Grants a 0-M Armored Suit if out of armor.",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Ultra Sphere",
        "type": "Megacharge",
        "category": "Healing",
        "effect": "Fully restores health and armor and overcharges both by +200.",
        "notes": "Grants an Elite Sentinel Armor if out of armor.",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },

    {
        "name": "UAC Ballistic Vest",
        "type": "Security Armor",
        "category": "Armor",
        "effect": "100 armor. 35% protection. 30% physical resistance.",
        "notes": "",
        "carriable": false,
        // "description": "Standard-issue armor commonly used by UAC marines. Very effective against bullets and blunt trauma, not so much against fireballs.",
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Adaptive Kinetic Armor",
        "type": "Security Armor",
        "category": "Armor",
        "effect": "120 armor. 35% protection. 60% physical resistance.",
        "notes": "",
        "carriable": false,
        // "description": "High-tech armor providing tremendous protection against physical damage due to its tough yet flexible material.",
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "0-M Armored Suit",
        "type": "Combat Armor",
        "category": "Armor",
        "effect": "200 armor. 50% protection. 10% global resistance.",
        "notes": "",
        "carriable": false,
        // "description": "Full-body armor worn by the best of the best. Allows its wearer to withstand significant punishment without dying.",
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Elite Sentinel Armor",
        "type": "Combat Armor",
        "category": "Armor",
        "effect": "300 armor. 60% protection. 20% global resistance.",
        "notes": "",
        "carriable": false,
        // "description": "An expensive masterfully crafted suit of armor, reserved for extremely dangerous operations.",
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "EOD Armored Suit",
        "type": "Combat Armor",
        "category": "Armor",
        "effect": "300 armor. 65% protection. 50% explosive resistance.",
        "notes": "",
        "carriable": false,
        // "description": "Full suit of polymer composite padded armor. Provides heavy protection to the wearer as well as resistance against explosives.",
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Demonic Plate Armor",
        "type": "Combat Armor",
        "category": "Armor",
        "effect": "300 armor. 66% protection. 50% fire resistance.",
        "notes": "",
        "carriable": false,
        // "description": "Full suit of polymer composite padded armor. Provides heavy protection to the wearer as well as resistance against explosives.",
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 1
    },

    {
        "name": "Bullet Pile",
        "type": "Small Bullet Pickup",
        "category": "Ammunition",
        "effect": "10 bullets.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Bullet Box",
        "type": "Large Bullet Pickup",
        "category": "Ammunition",
        "effect": "50 bullets.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Shotgun Shells",
        "type": "Small Shell Pickup",
        "category": "Ammunition",
        "effect": "4 shells.",
        "notes": "",
        "carriable": false,
        // "description": "A handful of shotgun shells made to be stuffed into shotguns.",
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Shell Box",
        "type": "Large Shell Pickup",
        "category": "Ammunition",
        "effect": "20 shells.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Rocket",
        "type": "Small Rocket Pickup",
        "category": "Ammunition",
        "effect": "1 rocket.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Rocket Box",
        "type": "Large Rocket Pickup",
        "category": "Ammunition",
        "effect": "5 rockets.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Energy Cell",
        "type": "Small Cell Pickup",
        "category": "Ammunition",
        "effect": "20 cells.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Energy Cell Pack",
        "type": "Large Cell Pickup",
        "category": "Ammunition",
        "effect": "100 cells.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Demonic Essence",
        "type": "Small Demonic Pickup",
        "category": "Ammunition",
        "effect": "5 demon energy.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Large Demonic Essence",
        "type": "Large Demonic Pickup",
        "category": "Ammunition",
        "effect": "25 demon energy.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Grenade",
        "type": "Small Grenade Pickup",
        "category": "Ammunition",
        "effect": "1 grenade.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Grenade Box",
        "type": "Large Grenade Pickup",
        "category": "Ammunition",
        "effect": "5 grenades.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },

    {
        "name": "Ammo Backpack",
        "type": "Capacity Increase",
        "category": "Powerup",
        "effect": "Doubled ammo capacity. Grants 10 bullets, 4 shells, 1 rocket, 20 cells and 5 grenades.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Resupply Pack",
        "type": "Capacity Increase",
        "category": "Powerup",
        "effect": "Doubled ammo capacity. Grants 50 bullets, 20 shells, 5 rockets, 100 cells and 10 grenades.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Magazine Pouch",
        "type": "Capacity Increase",
        "category": "Powerup",
        "effect": "Bullet ammo capacity increased by 20. Grants 20 bullets. Stacks up to five times.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Shell Bandolier",
        "type": "Capacity Increase",
        "category": "Powerup",
        "effect": "Shell ammo capacity increased by 8. Grants 8 shells. Stacks up to five times.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Rocket Bag",
        "type": "Capacity Increase",
        "category": "Powerup",
        "effect": "Rocket ammo capacity increased by 5. Grants 5 rockets. Stacks up to five times.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Portable Capacitor",
        "type": "Capacity Increase",
        "category": "Powerup",
        "effect": "Cell ammo capacity increased by 30. Grants 30 cells. Stacks up to five times.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Demonic Crystal",
        "type": "Capacity Increase",
        "category": "Powerup",
        "effect": "Demonic ammo capacity increased by 15. Grants 15 demon energy. Stacks up to five times.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Grenade Belt",
        "type": "Capacity Increase",
        "category": "Powerup",
        "effect": "Grenade capacity increased by 2. Grants 2 grenades. Stacks up to five times.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Computer Area Map",
        "type": "Map Reveal",
        "category": "Powerup",
        "effect": "Draws unvisited areas in the automap.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Terrain Analyzer",
        "type": "Map Reveal",
        "category": "Powerup",
        "effect": "Draws unvisited areas in the automap. 2 charges per pickup.",
        "notes": "",
        "carriable": true,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 1
    },
    {
        "name": "Radiation Shielding Suit",
        "type": "Hazard Protection",
        "category": "Powerup",
        "effect": "Protects against damaging floors for 60 seconds.",
        "notes": "Highly damaging floor types have a chance to bypass the suit's protection.",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Hazardous Environment Suit",
        "type": "Hazard Protection",
        "category": "Powerup",
        "effect": "Protects against damaging floors for 90 seconds.",
        "notes": "Cannot leak.",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Immuno-enhancer Suit",
        "type": "Hazard Protection",
        "category": "Powerup",
        "effect": "Protects against damaging floors and negative status effects for 60 seconds.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 2
    },
    {
        "name": "Speed Suit",
        "type": "Hazard Protection",
        "category": "Powerup",
        "effect": "Protects against damaging floors and grants increased movement speed for 60 seconds.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Blast Protection Suit",
        "type": "Hazard Protection",
        "category": "Powerup",
        "effect": "Protects against damaging floors and reduces self-damage by 95%.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 1
    },
    {
        "name": "Night-Vision Goggles",
        "type": "Light Amplification",
        "category": "Powerup",
        "effect": "Full-bright vision for 120 seconds.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Threat Detection Visor",
        "type": "Light Amplification",
        "category": "Powerup",
        "effect": "Full-bright vision and reveals invisible monsters for 120 seconds.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Weakness Scanner",
        "type": "Light Amplification",
        "category": "Powerup",
        "effect": "Last 120 seconds. While active, grants full-bright vision and attacks have a 10% chance of dealing triple damage.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },


    {
        "name": "Illusion Sphere",
        "type": "Buff Sphere",
        "category": "Powerup",
        "effect": "Lasts 60 seconds. While active, enemies targeting you have a chance to shoot in random directions",
        "notes": "Fixed offsets at -45°, 0° and 45°. Enemy sprite direction depends on the direction of the shot. Hopefully this prevents accidentally dodging into projectiles.",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Invisibility Sphere",
        "type": "Buff Sphere",
        "category": "Powerup",
        "effect": "Lasts 60 seconds. While active, enemies go after the last spot you made a sound at.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Damage Sphere",
        "type": "Buff Sphere",
        "category": "Powerup",
        "effect": "Double damage with all weapons for 45 seconds.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Shield Sphere",
        "type": "Buff Sphere",
        "category": "Powerup",
        "effect": "Take half damage for 60 seconds.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Weapon Sphere",
        "type": "Buff Sphere",
        "category": "Powerup",
        "effect": "Grants you a random Powerup weapon for 45 seconds.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Momentum Sphere",
        "type": "Buff Sphere",
        "category": "Powerup",
        "effect": "Grants you triple damage and invincibility until you take a hit.",
        "notes": "Has a 5 seconds grace period after being picked up.",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Invulnerability Sphere",
        "type": "Power Sphere",
        "category": "Powerup",
        "effect": "Immune to all damage for 30 seconds.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Doom Sphere",
        "type": "Power Sphere",
        "category": "Powerup",
        "effect": "Quad damage with all weapons and 50% damage resistance for 30 seconds.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Reflection Sphere",
        "type": "Power Sphere",
        "category": "Powerup",
        "effect": "Lasts 30 seconds. While active, you're immune to damage and all attacks bounce off of you towards the attacker, dealing triple the damage.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Absorption Sphere",
        "type": "Power Sphere",
        "category": "Powerup",
        "effect": "Lasts 30 seconds. While active, you're immune to damage and all attacks you take gives you health and armor regeneration until +200.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Nuke Sphere",
        "type": "Power Sphere",
        "category": "Powerup",
        "effect": "Immune to all damage for 30 seconds. Detonates a nuclear blast upon expiring.",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "God Sphere",
        "type": "Power Sphere",
        "category": "Powerup",
        "effect": "Lasts 30 seconds. While active, you're immune to damage and throw balls of divine energy that smite your enemies.",
        "notes": "Smite effect is identical to the Fury of the Archangel.",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Glory Sphere",
        "type": "Power Sphere",
        "category": "Powerup",
        "effect": "Lasts 30 seconds. While active, you're immune to damage and all melee attacks deal 5x the damage. Rip and tear!",
        "notes": "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 1
    },

    {
        "name": "Rune of Self-Sufficiency",
        "type": "Rune",
        "category": "Rune",
        "effect": "You gain passive regeneration, but health pickups are half as effective.",
        "notes": "",
        "carriable": true,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Rune of Herculeanism",
        "type": "Rune",
        "category": "Rune",
        "effect": "You are able to overheal with all health items up to +200, but your health decays when above 100.",
        "notes": "",
        "carriable": true,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Rune of Resourcefulness",
        "type": "Rune",
        "category": "Rune",
        "effect": "You passively regenerate ammo, but your reserves are cut in half.",
        "notes": "",
        "carriable": true,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Rune of Brute Force",
        "type": "Rune",
        "category": "Rune",
        "effect": "You gain a damage multiplier, which changes to a random number between 0.5 and 2, every 5 seconds.",
        "notes": "",
        "carriable": true,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Rune of Insensitivity",
        "type": "Rune",
        "category": "Rune",
        "effect": "You take 33% less damage, but your armor breaks twice as fast.",
        "notes": "",
        "carriable": true,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Rune of Hastiness",
        "type": "Rune",
        "category": "Rune",
        "effect": "You attack 50% faster, but each attack has a chance to be negated.",
        "notes": "",
        "carriable": true,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Rune of Impact",
        "type": "Rune",
        "category": "Rune",
        "effect": "You deal double damage, but attack half as fast.",
        "notes": "",
        "carriable": true,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Rune of Noncommitment",
        "type": "Rune",
        "category": "Rune",
        "effect": "You gain a big damage boost that rapidly decays when switching weapons, but your base damage is reduced.",
        "notes": "",
        "carriable": true,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Rune of Acceleration",
        "type": "Rune",
        "category": "Rune",
        "effect": "You gain attack speed for each enemy killed in the current level, but your base attack speed is reduced.",
        "notes": "",
        "carriable": true,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 0
    },
    {
        "name": "Rune of Prudence",
        "type": "Rune",
        "category": "Rune",
        "effect": "You gain an extra life, but your movement speed is reduced.",
        "notes": "Movement speed penalty is removed after death. Stacks with and takes priority over Salvation Spheres.",
        "carriable": true,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 1
    },
    {
        "name": "Rune of Evasiveness",
        "type": "Rune",
        "category": "Rune",
        "effect": "You have a chance to negate damage based on how fast you're running, but you take increased damage from all sources.",
        "notes": "",
        "carriable": true,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 1
    },
    {
        "name": "Rune of Purification",
        "type": "Rune",
        "category": "Rune",
        "effect": "Use while under the effects of a rune to remove its negative effects. This and the affected rune are both removed from your inventory on use.",
        "notes": "",
        "carriable": true,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 1
    },

    {
        "name": "Contract with Aamon",
        "type": "Contract",
        "category": "Contract",
        "effect": "You gain 2 Juvenile Cacodemon familiars.",
        "notes": "Familiars respawn 15 seconds after dying. Dropped by Cacodemon variants.",
        "carriable": true,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 1
    },
    // {
    //     "name": "Contract with Asmodeus",
    //     "type": "Contract",
    //     "category": "Contract",
    //     "effect": "Temporary powerups last longer.",
    //     "notes": "Dropped by Satyr variants.",
    //     "carriable": true,
    //     "description": "",
    //     "authorsnotes": "",
    //     "designnotes": "",
    //     "newstatus": 1
    // },
    // {
    //     "name": "Contract with Astaroth",
    //     "type": "Contract",
    //     "category": "Contract",
    //     "effect": "",
    //     "notes": "Dropped by Salamander variants.",
    //     "carriable": true,
    //     "description": "",
    //     "authorsnotes": "",
    //     "designnotes": "",
    //     "newstatus": 1
    // },
    {
        "name": "Contract with Azazel",
        "type": "Contract",
        "category": "Contract",
        "effect": "Enemies you kill have a chance of coming back to life on your side.",
        "notes": "Dropped by Archvile variants.",
        "carriable": true,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 1
    },
    {
        "name": "Contract with Baal",
        "type": "Contract",
        "category": "Contract",
        "effect": "Occasionally gain the effect of the Invisibility Sphere for 5 seconds.",
        "notes": "Dropped by Spectre variants.",
        "carriable": true,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 1
    },
    {
        "name": "Contract with Baphomet",
        "type": "Contract",
        "category": "Contract",
        "effect": "Having over 66% of a specific ammo type increases damage dealt by all weapons using that ammo type.",
        "notes": "No effect on weapons with infinite ammo. Dropped by Baron of Hell variants.",
        "carriable": true,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 1
    },
    {
        "name": "Contract with Beelzebub",
        "type": "Contract",
        "category": "Contract",
        "effect": "All health and armor bonuses are twice as effective, and all medical supplies heal an additional 5 health. No overcharge limit.",
        "notes": "Dropped by Mancubus variants.",
        "carriable": true,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 1
    },
    // {
    //     "name": "Contract with Belial",
    //     "type": "Contract",
    //     "category": "Contract",
    //     "effect": "Magic and Demonic weapons deal increased damage.",
    //     "notes": "Dropped by Heretic variants.",
    //     "carriable": true,
    //     "description": "",
    //     "authorsnotes": "",
    //     "designnotes": "",
    //     "newstatus": 1
    // },
    {
        "name": "Contract with Belphegor",
        "type": "Contract",
        "category": "Contract",
        "effect": "Double damage while standing still.",
        "notes": "Dropped by Arachnotron variants.",
        "carriable": true,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 1
    },
    {
        "name": "Contract with Leviathan",
        "type": "Contract",
        "category": "Contract",
        "effect": "The lower your health, the faster you attack.",
        "notes": "Dropped by Spiderdemon variants.",
        "carriable": true,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 1
    },
    // {
    //     "name": "Contract with Lilith",
    //     "type": "Contract",
    //     "category": "Contract",
    //     "effect": "",
    //     "notes": "Dropped by Succubus variants.",
    //     "carriable": true,
    //     "description": "",
    //     "authorsnotes": "",
    //     "designnotes": "",
    //     "newstatus": 1
    // },
    {
        "name": "Contract with Lucifer",
        "type": "Contract",
        "category": "Contract",
        "effect": "Increased damage while at max health.",
        "notes": "Dropped by Cyberdemon variants.",
        "carriable": true,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 1
    },
    {
        "name": "Contract with Mammon",
        "type": "Contract",
        "category": "Contract",
        "effect": "Enemies drop extra ammo when killed.",
        "notes": "Dropped by Hell Knight variants.",
        "carriable": true,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 1
    },
    {
        "name": "Contract with Moloch",
        "type": "Contract",
        "category": "Contract",
        "effect": "Enemies flinch more often and for longer.",
        "notes": "Dropped by Pain Elemental variants.",
        "carriable": true,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 1
    },
    // {
    //     "name": "Contract with Naberius",
    //     "type": "Contract",
    //     "category": "Contract",
    //     "effect": "",
    //     "notes": "Dropped by Hellhound variants.",
    //     "carriable": true,
    //     "description": "",
    //     "authorsnotes": "",
    //     "designnotes": "",
    //     "newstatus": 1
    // },
    {
        "name": "Contract with Paimon",
        "type": "Contract",
        "category": "Contract",
        "effect": "You gain 25% global resistance when out of armor.",
        "notes": "Dropped by Revenant variants.",
        "carriable": true,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 1
    },
    {
        "name": "Contract with Satan",
        "type": "Contract",
        "category": "Contract",
        "effect": "Permanent Berserk with increased effectiveness.",
        "notes": "Dropped by Fiend variants.",
        "carriable": true,
        "description": "",
        "authorsnotes": "",
        "designnotes": "",
        "newstatus": 1
    },

]