export default [
    {
        "name": "Healing Vial",
        "type": "Health Bonus",
        "category": "Healing",
        "effect" : "Restores 1 health. Can overcharge up to +100.",
        "notes" : "",
        "carriable": false,
        "description": "A small flask of mysterious blue liquid. Rapidly dissipates into the body when ingested and slightly accelerates cell regeneration.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Strong Healing Vial",
        "type": "Health Bonus",
        "category": "Healing",
        "effect" : "Restores 3 health. Can overcharge up to +100.",
        "notes" : "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Armor Shard",
        "type": "Armor Bonus",
        "category": "Healing",
        "effect" : "Restores 1 armor. Can overcharge up to +100.",
        "notes" : "Provides 20% protection if applied without armor.",
        "carriable": false,
        "description": "A small slab of metal that can be used to patch up damaged armor. Provides very little protection on its own.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Strong Armor Shard",
        "type": "Armor Bonus",
        "category": "Healing",
        "effect" : "Restores 3 armor. Can overcharge up to +100.",
        "notes" : "Provides 20% protection if applied without armor.",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": ""
    },
    
    {
        "name": "Stimpack",
        "type": "Small Health Pack",
        "category": "Healing",
        "effect" : "Restores 10 health.",
        "notes" : "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Berserk Syringe",
        "type": "Small Health Pack",
        "category": "Healing",
        "effect" : "Restores 20 health and grants Berserk for the rest of the level.",
        "notes" : "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Medikit",
        "type": "Large Health Pack",
        "category": "Healing",
        "effect" : "Restores 25 health.",
        "notes" : "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Field Kit",
        "type": "Large Health Pack",
        "category": "Healing",
        "effect" : "Restores 25 health.",
        "notes" : "",
        "carriable": true,
        "description": "",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Berserk Pack",
        "type": "Booster Pack",
        "category": "Healing",
        "effect" : "Restores 100 health and grants Berserk for the rest of the level.",
        "notes" : "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": ""
    },

    {
        "name": "Soul Sphere",
        "type": "Supercharge",
        "category": "Healing",
        "effect" : "Restores 100 health. Can overcharge up to +100.",
        "notes" : "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Life Sphere",
        "type": "Supercharge",
        "category": "Healing",
        "effect" : "Restores 150 health. Can overcharge up to +200.",
        "notes" : "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Mega Sphere",
        "type": "Megacharge",
        "category": "Healing",
        "effect" : "Fully restores health and armor and overcharges both by +100.",
        "notes" : "Grants a 0-M Armored Suit if out of armor.",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": ""
    },
    
    {
        "name": "UAC Ballistic Vest",
        "type": "Security Armor",
        "category": "Armor",
        "effect" : "100 armor. 35% protection. 40% physical resistance.",
        "notes" : "",
        "carriable": false,
        "description": "Standard-issue armor commonly used by UAC marines. Very effective against bullets and blunt trauma, not so much against fireballs.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "0-M Armored Suit",
        "type": "Combat Armor",
        "category": "Armor",
        "effect" : "200 armor. 50% protection. 10% global resistance.",
        "notes" : "",
        "carriable": false,
        "description": "Full-body armor worn by the best of the best. Allows its wearer to withstand significant damage without dying.",
        "authorsnotes": "",
        "designnotes": ""
    },

    {
        "name": "Ammo Backpack",
        "type": "Capacity Increase",
        "category": "Powerup",
        "effect" : "Doubled ammo capacity. Grants 10 bullets, 4 shells, 1 rocket and 20 cells.",
        "notes" : "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Magazine Pouch",
        "type": "Capacity Increase",
        "category": "Powerup",
        "effect" : "Bullet ammo capacity increased by 20. Grants 20 bullets. Stacks up to five times.",
        "notes" : "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Shell Bandolier",
        "type": "Capacity Increase",
        "category": "Powerup",
        "effect" : "Shell ammo capacity increased by 8. Grants 8 shells. Stacks up to five times.",
        "notes" : "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Rocket Bag",
        "type": "Capacity Increase",
        "category": "Powerup",
        "effect" : "Rocket ammo capacity increased by 5. Grants 5 rockets. Stacks up to five times.",
        "notes" : "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Portable Capacitor",
        "type": "Capacity Increase",
        "category": "Powerup",
        "effect" : "Cell ammo capacity increased by 30. Grants 30 cells. Stacks up to five times.",
        "notes" : "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Demonic Rune",
        "type": "Capacity Increase",
        "category": "Powerup",
        "effect" : "Demon ammo capacity increased by 15. Grants 15 demon energy. Stacks up to five times.",
        "notes" : "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Computer Area Map",
        "type": "Map Reveal",
        "category": "Powerup",
        "effect" : "Draws unvisited areas in the automap.",
        "notes" : "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Radiation Shielding Suit",
        "type": "Hazard Protection",
        "category": "Powerup",
        "effect" : "Protects against damaging floors for 60 seconds.",
        "notes" : "Highly damaging floor types have a chance to bypass the suit's protection.",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Hazardous Environment Suit",
        "type": "Hazard Protection",
        "category": "Powerup",
        "effect" : "Protects against damaging floors for 90 seconds.",
        "notes" : "Cannot leak.",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Speed Suit",
        "type": "Hazard Protection",
        "category": "Powerup",
        "effect" : "Protects against damaging floors and grants increases movement speed for 60 seconds.",
        "notes" : "Highly damaging floor types have a chance to bypass the suit's protection.",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Night-Vision Goggles",
        "type": "Light Amplification",
        "category": "Powerup",
        "effect" : "Full-bright vision for 120 seconds.",
        "notes" : "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": ""
    },

    {
        "name": "Bullet Pile",
        "type": "Small Bullet Pickup",
        "category": "Ammunition",
        "effect" : "10 bullets.",
        "notes" : "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Bullet Box",
        "type": "Large Bullet Pickup",
        "category": "Ammunition",
        "effect" : "50 bullets.",
        "notes" : "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Shotgun Shells",
        "type": "Small Shell Pickup",
        "category": "Ammunition",
        "effect" : "4 shells.",
        "notes" : "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Shell Box",
        "type": "Large Shell Pickup",
        "category": "Ammunition",
        "effect" : "20 shells.",
        "notes" : "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Rocket",
        "type": "Small Rocket Pickup",
        "category": "Ammunition",
        "effect" : "1 rocket.",
        "notes" : "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Rocket Box",
        "type": "Large Rocket Pickup",
        "category": "Ammunition",
        "effect" : "5 rockets.",
        "notes" : "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Energy Cell",
        "type": "Small Cell Pickup",
        "category": "Ammunition",
        "effect" : "20 cells.",
        "notes" : "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Energy Cell Pack",
        "type": "Large Cell Pickup",
        "category": "Ammunition",
        "effect" : "100 cells.",
        "notes" : "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": ""
    },

    {
        "name": "Illusion",
        "type": "Buff Sphere",
        "category": "Powerup",
        "effect" : "Lasts 60 seconds. While active, enemies have a chance to shoot in random directions",
        "notes" : "Fixed offsets at -45°, 0° and 45°. Enemy sprite direction depends on the direction of the shot. Hopefully this prevents accidentally dodging into projectiles.",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Invisibility",
        "type": "Buff Sphere",
        "category": "Powerup",
        "effect" : "Lasts 60 seconds. While active, enemies go after the last spot you made a sound at.",
        "notes" : "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Double Damage",
        "type": "Buff Sphere",
        "category": "Powerup",
        "effect" : "Double damage with all weapons for 45 seconds.",
        "notes" : "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Invulnerability",
        "type": "Power Sphere",
        "category": "Powerup",
        "effect" : "Immune to all damage for 30 seconds.",
        "notes" : "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Doom",
        "type": "Power Sphere",
        "category": "Powerup",
        "effect" : "Quad damage with all weapons and 50% damage resistance for 30 seconds.",
        "notes" : "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Reflection",
        "type": "Power Sphere",
        "category": "Powerup",
        "effect" : "Last 30 seconds. While active, all attacks bounce harmlessly off of you.",
        "notes" : "",
        "carriable": false,
        "description": "",
        "authorsnotes": "",
        "designnotes": ""
    },
]