export default [
    {
        "name": "Combat Knife",
        "fullname": "",
        "ammo": "N/A",
        "category": "Melee",
        "primary" : "Stab",
        "secondary" : "N/A",
        "notes" : "10x damage against unaware enemies.",
        "superior" : "Secondary attack parries enemy projectiles.",
        "durability": false,
        "description": "Standard-issue CQC weapon for those seeking a stealthier approach, combat in ammo-scarce environements, or just plain old getting close and personnal. Cuts and punctures hellspawn skin like a hot... well, knife through butter.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Brass Knuckles",
        "fullname": "",
        "ammo": "N/A",
        "category": "Melee",
        "primary" : "Punch",
        "secondary" : "N/A",
        "notes" : "5x damage when under the effects of Berserk.",
        "superior" : "Guaranteed flinch with increased duration.",
        "durability": false,
        "description": "The solution for those who have something to prove but don't want to feel limited by the fleshy padding wrapping their hands. Nothing like knocking out a demon in a single roid-fuelled punch.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Chainsaw",
        "fullname": "",
        "ammo": "N/A",
        "category": "Melee",
        "primary" : "Saw",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Kills stuns nearby demons. Duration and area are affected by the demon's max health.",
        "durability": false,
        "description": "Woodcutting tool turned demon ripper. Not the cleanest among melee weapons, but its crudeness has a certain charm to it. Now go find some meat.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Super Chainsaw",
        "fullname": "UAC Dual-Blade FTAU-8000 Chainsaw",
        "ammo": "N/A",
        "category": "Melee",
        "primary" : "Saw",
        "secondary" : "N/A",
        "notes" : "Lengthy cooldown after prolonged use.",
        "superior" : "No longer jams. Increased movement speed while revving.",
        "durability": false,
        "description": "Following the unexpected success of chainsaws on the battlefield, the next logical step would obviously be to double-down on the ripping and tearing. Painting your armor red has never been so easy, but the increased power required tends to jam the weapon after prolonged usage.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Plasma Saber",
        "fullname": "",
        "ammo": "N/A",
        "category": "Melee",
        "primary" : "Slash",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Shoots horizontal plasma beams.",
        "durability": false,
        "description": "Prehistoric technology meets post-space age material developpement. This plasma-fueled magic wand will sever, melt, lacerate and immolate any and all things unfortunate enough to make contact with it.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Blast Hammer",
        "fullname": "",
        "ammo": "Shells",
        "category": "Melee",
        "primary" : "Smash",
        "secondary" : "N/A",
        "notes" : "Reduced damage when out of ammo.",
        "superior" : "Kills increases the speed of the next swing and causes you to instantly dash to your target.",
        "durability": false,
        "description": "A large metal weight affixed on top of a pole is nothing you haven't seen before, but the surprise comes in the form of a 12 gauge frag round right in whatever freak's skull you just caved in. Demolition with a capital D.",
        "authorsnotes": "Basically KF2's Pulverizer.",
        "designnotes": ""
    },
    {
        "name": "Power Fist",
        "fullname": "",
        "ammo": "N/A",
        "category": "Melee",
        "primary" : "Charged Uppercut",
        "secondary" : "N/A",
        "notes" : "Damage depends on amount of charge. 2x damage when under the effects of Berserk.",
        "superior" : "Store charge with secondary fire. Increased maximum charge.",
        "durability": false,
        "description": "Ever wanted to not only kill a demon in a single punch, but also knock its head clean off its shoulders straight into the stratosphere? Do you feel disgusted by the limitations of the human body? Are you currently in rehab for steroid abuse? (we don't judge) If you answered yes to any of these questions, here's the weapon just for you.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Guntlet",
        "fullname": "",
        "ammo": "Shells",
        "category": "Melee",
        "primary" : "Shotgun jab",
        "secondary" : "Shotgun uppercut",
        "notes" : "2x damage when under the effects of Berserk - this does include the shotgun blast. Uppercut deals more damage; jab causes pellets to hit enemies behind the target on kill.",
        "superior" : "Can parry projectiles and triples the shotgun blast damage when doing so. Parrying with an uppercut makes you look cool but has no practical use.",
        "durability": false,
        "description": "Typographic error turned monster tenderiser. Negates the inherent inaccuracy of shotgun shells by eliminating the range variable completely. Your money back if it explodes in your hand.",
        "authorsnotes": "The GANTLET.",
        "designnotes": ""
    },
    {
        "name": "Laser Drill",
        "fullname": "",
        "ammo": "N/A",
        "category": "Melee",
        "primary" : "Laser beam",
        "secondary" : "Overclocked beam",
        "notes" : "Secondary attack damages the weapon and requires a cooldown after firing.",
        "superior" : "Unbreakable. Primary attack has drastically increased range.",
        "durability": true,
        "description": "A hand-held power tool used to harvest minerals from space rocks using a (literal) myriad of lasers converging into a single point. If you've ever burned ants with a magnifying glass as a kid, this machine will make you feel right at home.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "DNA Blade",
        "fullname": "",
        "ammo": "N/A",
        "category": "Melee",
        "primary" : "Stab",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Target explodes on death, dealing heavy damage to nearby demons of the same species.",
        "durability": true,
        "description": "Experimental knife developped for quickly eliminating difficult to kill targets. The blade can be detached, releasing a special chemical that violently reacts with demonic DNA. Spontaneous destruction of target usually occurs.",
        "authorsnotes": "Inspired by the Longinus Knife from Xionic Madness.",
        "designnotes": ""
    },

    {
        "name": "Pistol",
        "fullname": "ACG Delta-10",
        "ammo": "Bullets",
        "category": "Sidearm",
        "primary" : "Fire",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Fires rockets, consumes 4 bullets.",
        "durability": false,
        "description": "Nothing wrong with a good old self-loader. One of these and 50 bullets, just enough to get the party started.",
        "authorsnotes": "",
        "designnotes": "The first weapon I drew. Looks as generic as it gets."
    },
    {
        "name": "Lucky Pistol",
        "fullname": "",
        "ammo": "Bullets",
        "category": "Sidearm",
        "primary" : "Fire",
        "secondary" : "N/A",
        "notes" : "10% chance to deal 5x damage",
        "superior" : "Additional 5% chance to deal 10x damage. Stacks with the base effect.",
        "durability": false,
        "description": "A gold-plated pistol with ivory grips and fitted with an engraved suppressor; most likely a collection piece. Altough obsolete and completely outclassed as a combat weapon, it gives off a certain aura that makes vital shots easier to hit.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Magnum",
        "fullname": "",
        "ammo": "Bullets x3",
        "category": "Sidearm",
        "primary" : "Fire",
        "secondary" : "N/A",
        "notes" : "Requires reloading. Small delay before firing.",
        "superior" : "No firing delay. Extremely fast drawing and holstering speed. Passively builds up focus. Focus is lost when firing. Triple damage at max focus.",
        "durability": false,
        "description": "Revolvers might be a little too old-school in an age of plasma guns and demon magic, but their relative simplicity makes them ideal candidates for jamming the biggest baddest ammunition available, and sometimes that's just what you need.",
        "authorsnotes": "",
        "designnotes": "Based on an old revolver design of mine, with a little less Raging Bull and a little more Colt Python."
    },
    {
        "name": "Handcannon",
        "fullname": "",
        "ammo": "Bullets x10",
        "category": "Sidearm",
        "primary" : "Fire",
        "secondary" : "N/A",
        "notes" : "Overkill damage pierces enemies.",
        "superior" : "Instant reload on kill.",
        "durability": false,
        "description": "Magnum sniper rounds in a single-shot package that fits in your pocket. The absolute final word in one handed caliber pissing matches.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Hip-fire",
        "fullname": "",
        "ammo": "Bullets",
        "category": "Sidearm",
        "primary" : "Fire",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Automatic and guns akimbo.",
        "durability": false,
        "description": "Originally developped to give wounded soldiers a way to effectively defend themselves with only one arm, this little wonder of small arms developpement gives the shooter exceptional accuracy even without using the sights. A self-adjusting barrel-aligned laser system ensures you will always hit where you aim. Even better if you still have 2 functional arms.",
        "authorsnotes": "",
        "designnotes": "The low bore axis is inspired by the Laugo Alien."
    },
    {
        "name": "Smart Gun",
        "fullname": "",
        "ammo": "Bullets x2",
        "category": "Sidearm",
        "primary" : "Smart fire",
        "secondary" : "Lock-on",
        "notes" : "Requires reloading.",
        "superior" : "Each locked target increases damage.",
        "durability": false,
        "description": "High capacity revolver that aims itself through a mix of target recognition sensors and computer-assisted electromagnetic adjusters. Is able to lock on to multiple targets before firing at all of them in sequence.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Security Pistol",
        "fullname": "",
        "ammo": "Cells",
        "category": "Sidearm",
        "primary" : "Plasma shot",
        "secondary" : "Charged shot",
        "notes" : "Each charge level consumes 1 extra ammo up to 5.",
        "superior" : "Maximum charge increases to 10. Fully charged shots create a stunning shockwave on impact.",
        "durability": false,
        "description": "Plasma is all the rage these days, so it was only a matter of time before these became a thing. Low-powered plasma pistols are great for pacifying human threats without killing them, but with demons outnumbering criminals, full-power quickly became the norm among security guards.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Flare Gun",
        "fullname": "",
        "ammo": "Rockets",
        "category": "Sidearm",
        "primary" : "Flare",
        "secondary" : "N/A",
        "notes" : "Projectile sticks to enemies and deals constant fire damage.",
        "superior" : "Secondary attack loads extra flares up to 5. Firing shoots all loaded flares in an arc.",
        "durability": false,
        "description": "An emergency tool used to signal your position to whoever is coming to save you. But in a real emergency you can also use this to cook demon flesh extra crispy from a relatively safe distance.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "MMP-50",
        "fullname": "",
        "ammo": "Bullets x2",
        "category": "Sidearm",
        "primary" : "Auto-fire",
        "secondary" : "N/A",
        "notes" : "Spread decreases rapidly when firing.",
        "superior" : "First 3 shots of a burst are fired at increased speed with no spread increase.",
        "durability": false,
        "description": "\"Magnum\" and \"Machine-pistol\" are not two words you commonly see together and for good reason. Don't try and shoot it à la John Woo, as the human wrist has not evolved to withstand 2 kilojoules of force over 10 times per second.",
        "authorsnotes": "Inspired by the real life full-auto Desert Eagle.",
        "designnotes": ""
    },
    {
        "name": "SMG",
        "fullname": "",
        "ammo": "Bullets",
        "category": "Sidearm",
        "primary" : "Auto-fire",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Consecutive shots on the same target increases damage.",
        "durability": false,
        "description": "A weapon type that didn't get much of a chance to prove itself originally, but as pistol cartridges got more powerful it finally managed to find a niche amongst users with a preference for more controllable, rapid-fire weapons.",
        "authorsnotes": "",
        "designnotes": "Some weird mash of a Kriss Vector and a UMP."
    },
    {
        "name": "Sawn-off",
        "fullname": "",
        "ammo": "Shells",
        "category": "Sidearm",
        "primary" : "Double-barrel (x16)",
        "secondary" : "Single-barrel (x8)",
        "notes" : "",
        "superior" : "Guns akimbo.",
        "durability": false,
        "description": "Diminutive iteration of the classic double-barrel we all know and love. High maneuverability and reload speed at the cost of severely decreased accuracy. Usable one-handed for the expert gunslingers out there.",
        "authorsnotes": "Basically Blood's shotgun.",
        "designnotes": ""
    },
    {
        "name": "Giga-Volt",
        "fullname": "",
        "ammo": "N/A",
        "category": "Sidearm",
        "primary" : "Taser shot",
        "secondary" : "N/A",
        "notes" : "Discharge stops prematurely if a solid surface breaks line of sight with the target.",
        "superior" : "Target explodes on death.",
        "durability": true,
        "description": "Your average security stun gun this is not. Once attached, the electrodes conduct electricity at rates comparable to electric chairs, and only come off upon the target's demise or if line of sight is broken. As a safety measure, the battery must be changed after each shot, regardless of the length of the previous discharge.",
        "authorsnotes": "Inspired by the Taser from the Heli Attack series.",
        "designnotes": ""
    },
    
    {
        "name": "Shotgun",
        "fullname": "",
        "ammo": "Shells",
        "category": "Shotgun",
        "primary" : "Horizontal buckshot x8",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "x8 damage. Pellet damage doesn't stack anymore.",
        "durability": false,
        "description": "With close-range encounters becoming more prevalent, shotguns began to see more use as the range of rifles wasn't as needed anymore. If problem persists after treatment, keep treating until the problem goes away.",
        "authorsnotes": "Superior is inspired by how shotguns work in PAYDAY 2.",
        "designnotes": "Like the Pistol, there's nothing really special about this one."
    },
    {
        "name": "Rifled Shotgun",
        "fullname": "SENS Power Pump w/ Slug Shells",
        "ammo": "Shells",
        "category": "Shotgun",
        "primary" : "Slug",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Pierces up to 3 enemies.",
        "durability": false,
        "description": "Firing a single projectile per shot might seem antithetical to what a shotgun is best for, but it does have the precision and range advantage with a proper setup. You could use regular buckshot with this gun, but the rifled barrel ironically makes the spread worse. Some people even like to run these with explosive payloads when rockets are in short supply.",
        "authorsnotes": "",
        "designnotes": "The general shape of an 870 Express with a SPAS-12 pump."
    },
    {
        "name": "Blast Shotgun",
        "fullname": "",
        "ammo": "Shells",
        "category": "Shotgun",
        "primary" : "Blast",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Wider blast that knocks enemies back.",
        "durability": false,
        "description": "A gun that shoots no bullets, instead substituting the standard buckshot with an explosive compound, turning this shotgun into a close-range shockwave dispenser. Good alternative to a heavy machine-gun.",
        "authorsnotes": "Inspired by the Metal Slug shotgun.",
        "designnotes": ""
    },
    {
        "name": "Terminator Shotgun",
        "fullname": "",
        "ammo": "Shells",
        "category": "Shotgun",
        "primary" : "Circle buckshot x10",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Fires an extra high-damage pellet with perfect accuracy.",
        "durability": false,
        "description": "An alternate solution to the shooting buckshot problem. A lever isn't as straightforward as a pump, but the gun makes up for it with the ability to use bigger shells with higher pellet counts. Don't try to flip-cock it before consulting a gunsmith if you don't want to consult a doctor afterwards.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Combat Shotgun",
        "fullname": "",
        "ammo": "Shells",
        "category": "Shotgun",
        "primary" : "Buckshot x8",
        "secondary" : "N/A",
        "notes" : "Requires reloading.",
        "superior" : "No reloading.",
        "durability": false,
        "description": "All the boom of a shotgun without all that pumping and shell inserting nonsense. Semi-automatic means a higher rate of fire, and box magazines makes reloading in the heat of combat painless. Sure, it may not be as cool, but cool doesn't keep you out of the grave.",
        "authorsnotes": "",
        "designnotes": "A Saiga with an AR-15 charging handle and a somewhat Striker-ey overslung stock."
    },
    {
        "name": "40mm Shotgun",
        "fullname": "",
        "ammo": "Rockets",
        "category": "Shotgun",
        "primary" : "Buckshot x20",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Knocks the user backward when airborne.",
        "durability": false,
        "description": "Like a snake biting its tail, this \"shotgun\" is actually a pump-action grenade-launcher, loaded with grenades that actually fire buckshot. Clunky and hard to use, at the very least it tends to calm down whatever is on the receiving end very quickly.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Gyrojet Shotgun",
        "fullname": "",
        "ammo": "Rockets",
        "category": "Shotgun",
        "primary" : "Mini-rockets x5",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Additional sparkly explosions.",
        "durability": false,
        "description": "Gyrojet technology has been in limbo ever since its inception due to poor accuracy and legal issues. Decades later and with the constant threat of demonic attacks, research has progressed to the point where pump-action rocket-swarm-launchers are not only possible but effective as well.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Chromatic Shotgun",
        "fullname": "",
        "ammo": "Shells",
        "category": "Shotgun",
        "primary" : "Red spread x5 | Green beam | Blue blast",
        "secondary" : "Cycle between colors",
        "notes" : "",
        "superior" : "Combines all fire modes in one for double the ammo cost.",
        "durability": false,
        "description": "Killer colors! An arcane weapon that fires different kinds of projectiles out of a single ammo type.",
        "authorsnotes": "Based on Alien Vendetta's Map31.",
        "designnotes": ""
    },
    
    {
        "name": "Boomstick",
        "fullname": "",
        "ammo": "Shells",
        "category": "SSG",
        "primary" : "Double-barrel (x20)",
        "secondary" : "Single barrel (x10)",
        "notes" : "Increased accuracy on secondary fire.",
        "superior" : "Extra short-range pellets.",
        "durability": false,
        "description": "Who would have thought that double-barreled shotguns - a staple of the civilian market - would see widespread military use? Centuries of firearm evolution, tactical accessories, integrated computing, and what comes out on top? Two metal tubes loaded with buckshot.",
        "authorsnotes": "Yeah I didn't want to have Super Shotgun as both a category name and a weapon name.",
        "designnotes": "Generic side-by-side. The markings on the stock stand for 9, 4, and Romero."
    },
    {
        "name": "Drilling Shotgun",
        "fullname": "",
        "ammo": "Shells | Bullets x5",
        "category": "SSG",
        "primary" : "Buckshot x10",
        "secondary" : "Rifle shot",
        "notes" : "",
        "superior" : "Killing any enemy with buckshot reloads the rifle shot and vice-versa.",
        "durability": false,
        "description": "A survival shotgun with an underbarrel(s) high-power rifle. Lacks the double-trigger system that normally allows both barrels to be fired at once.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Slayer Shotgun",
        "fullname": "",
        "ammo": "Shells",
        "category": "SSG",
        "primary" : "Double-barrel (x20)",
        "secondary" : "Meat-hook",
        "notes" : "",
        "superior" : "Grappling hook sets target on fire.",
        "durability": false,
        "description": "A heavily modified side-by-size coach gun fitted with a grappling hook that provides fantastic mobility for daredevils, though its lack of stock or ability to fire single barrels tend to turn off who prefer not getting right in the demons' faces.",
        "authorsnotes": "",
        "designnotes": "I try to stay away from directly copying designs but I couldn't really with this one. The spike on the grip is my way of making it a bit less of a ripoff."
    },
    {
        "name": "Harpooner",
        "fullname": "",
        "ammo": "Shells",
        "category": "SSG",
        "primary" : "Harpoon",
        "secondary" : "Double-barrel (x20)",
        "notes" : "Harpoon doesn't work on boss enemies.",
        "superior" : "Extra damage to harpooned enemies.",
        "durability": false,
        "description": "The Slayer Shotgun concept turned on its head. The harpoon brings the demons right to you, and a double fistfull of buckshot makes sure they won't dare try to bite back.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Hyper Shotgun",
        "fullname": "",
        "ammo": "Shells",
        "category": "SSG",
        "primary" : "Double-barrel (x20)",
        "secondary" : "Single barrel (x10)",
        "notes" : "Requires reloading. Increased accuracy on secondary fire.",
        "superior" : "Can fire 2 extra shells before pumping.",
        "durability": false,
        "description": "The firepower of a double-barrel with the fire rate of a pump-action. The bullpup design may be a pain to reload, but when it's loaded, it's out for blood.",
        "authorsnotes": "",
        "designnotes": "Based on the Quake 2 SSG, with a stock straight out of a KSG. Barrels are in an over-under configuration to work around the limitations of 2D drawings."
    },
    {
        "name": "Quad Shotgun",
        "fullname": "",
        "ammo": "Shells",
        "category": "SSG",
        "primary" : "Quad-barrel (x40)",
        "secondary" : "Double-barrel (x20)",
        "notes" : "",
        "superior" : "Meatshots stuns and knocks back the target.",
        "durability": false,
        "description": "2 barrels of buckshot can bruise the shoulder of an untrained shooter. 4 barrels will most likely relocate your shoulder and not be painless about it. But hey, at least you're not on the other end.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Machreaper",
        "fullname": "",
        "ammo": "Cells x10",
        "category": "SSG",
        "primary" : "Shockwave",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Stuns enemies. Extra damage to stunned enemies.",
        "durability": false,
        "description": "This shotgun fires a high-powered supersonic shockwave over a very short distance. Normally, it would take some time for the capacitors to recharge between each shot, but it's also fitted with a kinetic supercharger, allowing you to accelerate the process with up to 2 actions of the lever.",
        "authorsnotes": "Blatantly ripped from Final Doomer. I just love that gun.",
        "designnotes": ""
    },
    {
        "name": "Jackhammer",
        "fullname": "",
        "ammo": "Shells",
        "category": "SSG",
        "primary" : "Auto-fire (x8)",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Fires in bursts of 2 with no delay. Second shot consumes no ammo.",
        "durability": true,
        "description": "A tiny little gun that triples in weight when loaded, way too light to absorb any recoil, basically zero precision, fires entirely too quickly due to how short the bolt is, and so crudely made it would make any gunsmith cry. The upside? Unparalleled flesh tenderiser.",
        "authorsnotes": "",
        "designnotes": ""
    },

    {
        "name": "Assault Rifle",
        "fullname": "",
        "ammo": "Bullets",
        "category": "Automatic",
        "primary" : "Auto-fire",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Increased rate of fire on kill",
        "durability": false,
        "description": "A mainstay of any solider's loadout since the middle of the 20th century. This jack-of-all-trades is good for precision and rapid-fire alike.",
        "authorsnotes": "",
        "designnotes": "Loosely based on the rifles found in the zombieman and player sprites. Features a G36-style charging handle on an otherwise pretty AR-15 looking gun."
    },
    {
        "name": "Chimera",
        "fullname": "",
        "ammo": "Bullets x2",
        "category": "Automatic",
        "primary" : "Auto-fire",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Fires 4 bullets per shot. Decreased damage.",
        "durability": false,
        "description": "Multi-barreled rifles haven't really had any kind of success before hell invaded, but when the strategy revolves around dispensing as much lead as possible, who's gonna say no to something that does it twice as much?",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Hyperburst",
        "fullname": "",
        "ammo": "Bullets",
        "category": "Automatic",
        "primary" : "Burst x3",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Secondary fire shoots 3 bursts at once in a horizontal spread.",
        "durability": false,
        "description": "Though mechanically complex and a pain to manufacture, this rifle has the distinct advantage of firing a burst of bullets quicker than the time it takes for the shooter to get hit with recoil. While not as strong individually, the rapid repeated bullet impacts have an easier time getting demons to flinch.",
        "authorsnotes": "",
        "designnotes": "We have the G11 at home. At least it's not BOCW's idiotic design."
    },
    {
        "name": "Chaingun",
        "fullname": "",
        "ammo": "Bullets",
        "category": "Automatic",
        "primary" : "Auto-fire",
        "secondary" : "Rapid-fire",
        "notes" : "Secondary fire can overheat. ",
        "superior" : "Increased overheat capacity and reduced delay when overheating.",
        "durability": false,
        "description": "The advantage of using electricity to power your gun it that you can directly control the rate of fire. In the case of prolonged rapid-fire, the gun has a quick-change rotating barrel assembly, allowing continued usage without damaging the overheated barrels.",
        "authorsnotes": "The multi-barrel gimmick is a riff on DOOM's \"chaingun\"",
        "designnotes": "Based on the minigun from Commando 2 with some M249 elements tacked on."
    },
    {
        "name": "GPMG",
        "fullname": "",
        "ammo": "Bullets x2",
        "category": "Automatic",
        "primary" : "Auto-fire",
        "secondary" : "",
        "notes" : "",
        "superior" : "Drastically increased fire rate and bullet spread.",
        "durability": false,
        "description": "Stands for General Purpose Machine-Gun. Named this way due to its ammo being strong enough to give the gun versatility, such as suppressive fire, destroying unarmored vehicles, or spitting enough lead to make customers not need to come back for more. Somehow usable one-handed, as the high recoil is enough to perfectly counteract its weight.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Nailgun",
        "fullname": "",
        "ammo": "Bullets x2",
        "category": "Automatic",
        "primary" : "Low-pressure rapid fire",
        "secondary" : "High-pressure precision fire",
        "notes" : "Pierces through enemies.",
        "superior" : "Fires both barrels at once",
        "durability": false,
        "description": "Double-barreled pneumatic hardware dispenser. Nails are dense enough to pierce through flesh like a hot knife through butter, though the extra mass limits their velocity severely.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Metalstorm",
        "fullname": "",
        "ammo": "Bullets",
        "category": "Automatic",
        "primary" : "Burst x36",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Ammo consumption reduced to 24 per burst",
        "durability": false,
        "description": "Taking what the Hyperburst does and jacking it up even higher. The Metalstorm has dozens of barrels loaded with caseless ammo, ready to be fired synchronously through electric pulses and creating a wall of bullets dense enough to block out the sun.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Minigun",
        "fullname": "",
        "ammo": "Bullets",
        "category": "Automatic",
        "primary" : "Brrrrt",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Increased accuracy over time.",
        "durability": true,
        "description": "Often misnamed as chainguns, miniguns are functionally similar, but cycle through multiple barrels as they fire, whilst chainguns only use one at a time. Multiple barrels allows for massive uninterrupted streams of bullets, but make accurate aiming practically impossible.",
        "authorsnotes": "",
        "designnotes": ""
    },

    {
        "name": "DMR",
        "fullname": "",
        "ammo": "Bullets x2",
        "category": "Precision",
        "primary" : "Fire",
        "secondary" : "",
        "notes" : "",
        "superior" : "Auto-fire",
        "durability": false,
        "description": "A more precision-focused weapon platform. Even though the bigger ammunition was originally used for its range, it's its stopping power that got these rifles to keep a niche in the world demon killing.",
        "authorsnotes": "",
        "designnotes": "I was originally going for a rectangular SVD kind of design, but decided to incorporate a bit of RX4 into it. I really like how sleek it looks."
    },
    {
        "name": "Infantry Rifle",
        "fullname": "",
        "ammo": "Bullets x2",
        "category": "Precision",
        "primary" : "Fire",
        "secondary" : "Bayonet thrust",
        "notes" : "Requires reloading.",
        "superior" : "Last shot deals 50% more damage for each bullet in the mag.",
        "durability": false,
        "description": "One the earliest mass-produced semi-automatic rifles in human history. Widely popular for its vintage wooden look and distinctive \"ping\" sound it makes when the clip has been emptied. Pointy stick included for good old infantry charges.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Gauss Rifle",
        "fullname": "",
        "ammo": "Bullets x2",
        "category": "Precision",
        "primary" : "Fire",
        "secondary" : "N/A",
        "notes" : "Infinite piercing",
        "superior" : "Damage increases for every enemy pierced.",
        "durability": false,
        "description": "With constant technological advancements in the fields of electricity and electronics came the democratisation of coilguns, where electromagnetic forces are used to sling bullets forwards at high enough velocities to pierce multiple layers of hellspawn. The quick charging and decharging of the coils also give this weapon its distinctive firing sound.",
        "authorsnotes": "",
        "designnotes": "Yeah that's an M16 stock and a Tavor grip. The circles on the side are supposed to be capacitors, the thing in the stock is the battery and whatever the sight rests on has an ammo counter in the back."
    },
    {
        "name": "Sniper Rifle",
        "fullname": "",
        "ammo": "Bullets x8",
        "category": "Precision",
        "primary" : "Fire",
        "secondary" : "Focus",
        "notes" : "Charging focus increases damage, up to 150%. Lower FOV and slower movement while focused.",
        "superior" : "Explosion on full focus.",
        "durability": false,
        "description": "A professional's weapon of choice. For the sedentary types and those who prefer shooting stuff without being shot back.",
        "authorsnotes": "Focus is based on the sniper rifle charge mechanic from TF2. Superior used to be explosive headshots, but I felt it went against the spirit of the game.",
        "designnotes": "You know what? Fuck you. *bullpups your AWM*"
    },
    {
        "name": "Double Tap",
        "fullname": "",
        "ammo": "Bullets x4",
        "category": "Precision",
        "primary" : "Fire",
        "secondary" : "N/A",
        "notes" : "Can fire twice before rechambering. Second consecutive shot on the same target deals triple damage.",
        "superior" : "Can tag up to 2 different enemies at once. Secondary fire deals damage to all enemies between the tagged targets.",
        "durability": false,
        "description": "A unique concept for a weapon that rewards skilled shooters with increased lethality. Bullets are briefly supercharged at different polarities when fired, causing an intense electric shock to the target after 2 successful consecutive hits. ",
        "authorsnotes": "Inspired by Advanced Warfare's NA-45. A CoD gun in my DOOM game, what has the world come to?",
        "designnotes": ""
    },
    {
        "name": "Anti-Materiel Rifle",
        "fullname": "",
        "ammo": "Bullets x20",
        "category": "Precision",
        "primary" : "Fire",
        "secondary" : "Focus",
        "notes" : "Charging focus increases damage, up to 150%. Lower FOV and slower movement while focused. Overkill damage pierces enemies.",
        "superior" : "Overkills explode the target.",
        "durability": false,
        "description": "As the name implies, this kind of rifle is best used against armored equipment and tends to be overkill for target elimination - that is, if said target doesn't takes magnitudes more punishment than any human would. Mind the recoil.",
        "authorsnotes": "",
        "designnotes": ""
    },
    
    {
        "name": "Rocket Launcher",
        "fullname": "",
        "ammo": "Rockets",
        "category": "Launcher",
        "primary" : "Rocket",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Rockets must travel 128 units before arming. Unarmed rockets extra impact damage. Secondary fire shoots pre-armed rockets for rocket-punching or rocket-jumping.",
        "durability": false,
        "description": "With bigger demons comes the need for bigger weaponry. Unlike older rocket launcher models, this one shoots slower rockets that consume less fuel and produce little to no back-blast, allowing usage in crowded environments.",
        "authorsnotes": "",
        "designnotes": "It's kind of a mess honestly. I almost gave it a muzzle brake before remembering rocket launchers don't need those."
    },
    {
        "name": "Heat Seeker",
        "fullname": "",
        "ammo": "Rockets",
        "category": "Launcher",
        "primary" : "Homing missile",
        "secondary" : "Guided missile",
        "notes" : "",
        "superior" : "Increased damage to flying enemies.",
        "durability": false,
        "description": "The ever increasing frequency of flying enemies called for a way to hit them with rockets more reliably. The targetting system causes a bit of delay between shots, but such the price of making missing your target an actual challenge.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Hellstorm",
        "fullname": "",
        "ammo": "Rockets",
        "category": "Launcher",
        "primary" : "Rocket auto-fire",
        "secondary" : "N/A",
        "notes" : "Lowers movement speed when firing.",
        "superior" : "No movement penalty.",
        "durability": false,
        "description": "Another shining example of quantity over quality, this weapon launches a volley of missiles at a rate high enough to qualify as suppressive fire. It might be a pain to carry and on the shoulder, but firing is a such a rush that it just keeps you coming back for more.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Grenade Launcher",
        "fullname": "",
        "ammo": "Rockets",
        "category": "Launcher",
        "primary" : "Grenade",
        "secondary" : "N/A",
        "notes" : "Grenade bounces against solid surfaces.",
        "superior" : "Increased damage after one bounce.",
        "durability": false,
        "description": "Sometimes, explosives need a little more subtlelty than destroying what directly in front of you. The grenades can be lobbed over wall, around corners, or worst case scenario, straight back at you. Someone could lose an eye.",
        "authorsnotes": "",
        "designnotes": "I really wanted to have the leaf sight on the front, but alas I chose practicality over style this time. The foregrip is foldable à la SR3-M, and the stock is just that generic AR-15 stock. Magazine is on the other side, it's basically that side revolving mag you can find on that one rocket launcher sprite."
    },
    {
        "name": "Assault Launcher",
        "fullname": "",
        "ammo": "Rockets",
        "category": "Launcher",
        "primary" : "Grenade auto-fire",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Consecutive shots on the same target increases blast damage and radius.",
        "durability": false,
        "description": "Slow-moving projectiles might do the trick for crowds and more sluggish targets, but there are some just nimble enough to consistently dodge or worse create unnecessary danger close situations. Reduced explosive radius, increased rate of fire and high-capacity magazines should give you just the edge you need against these pesky buggers.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Napalm Launcher",
        "fullname": "",
        "ammo": "Rockets x2",
        "category": "Launcher",
        "primary" : "Napalm grenade",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "More fire.",
        "durability": false,
        "description": "It's a mystery why most of the inhabitants of a place filled with fire and brimstone aren't immune to said fire and brimstone, but it does provide a fantastic crowd control opportunity and the simple pleasures of the smell of cooked demonic meat.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Frag Launcher",
        "fullname": "",
        "ammo": "Rockets",
        "category": "Launcher",
        "primary" : "Frag grenade",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Increased fragment amount. Fragments pierces through enemies.",
        "durability": false,
        "description": "Explosions are nice and all, but they tend to lose effectiveness over range. Fragmentation helps turn even the nastiest of misses into successful improvised acupuncture sessions. ",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Scorpion Crossbow",
        "fullname": "",
        "ammo": "Rockets",
        "category": "Launcher",
        "primary" : "Explosive bolts x3",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Bolts split into 2 after some travel time.",
        "durability": false,
        "description": "Modern propellants too fancy for you? Nostalgic for the 13th century? Maybe you're just longing for a little refinement to long-range explosive delivery. Either way, the Scorpion is the latest installement for the ones looking for an excuse to go full medieval.",
        "authorsnotes": "Inspired by the Commando 2 crossbow. It's actually named the Logan in that game, but Scorpion sounds cooler. Besides, Scorpion is the bow's name and they both work the same way, so who cares.",
        "designnotes": ""
    },
    {
        "name": "Howitzer",
        "fullname": "",
        "ammo": "Rockets x2",
        "category": "Launcher",
        "primary" : "Explosive shell",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Scatters explosives on impact.",
        "durability": false,
        "description": "The term \"Howitzer\" generally designates a piece of artillery that can fire both directly forwards and high up in the air - in this case, man-portable artillery. You may not care about the math behind ballistic trajectories, but \"man-portable artillery\" is really all you need to remember.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Cyber-Launcher",
        "fullname": "",
        "ammo": "Rockets",
        "category": "Launcher",
        "primary" : "Rocket burst x3",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Fires 2 additional mini seeking rockets per shot.",
        "durability": false,
        "description": "The might of a Cyberdemon in your hand. State of the art inertia reduction technolgy allows it to fire at a faster rate without the risk of the user losing control of the weapon and shooting rockets where they shouldn't be shot.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Rail Cannon",
        "fullname": "",
        "ammo": "Rockets",
        "category": "Launcher",
        "primary" : "Rail",
        "secondary" : "N/A",
        "notes" : "Infinite piercing",
        "superior" : "Bounces twice against solid surfaces.",
        "durability": true,
        "description": "Another man-protable artillery piece, mixed with fancy electric techno-magic. There's no explosive in the payload, instead relying on the projectile's mass and the extreme velocity of the railgun system to pierce basically anything.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Dragon Destructor",
        "fullname": "",
        "ammo": "Rockets x3",
        "category": "Launcher",
        "primary" : "Dragon rocket",
        "secondary" : "",
        "notes" : "Loses \"damage momentum\" when piercing enemies and explodes when it reaches 0. Initial momentum is equal to blast damage.",
        "superior" : "Enemies whose max health is under 10% of the dragon rocket's damage don't incur any momentum loss.",
        "durability": true,
        "description": "A little bit of style in a world of utilitarian designs. Launches a supermassive explosive that barrels through fodder and explodes when it hits a wall - fleshy or otherwise. A good grip is required as to make sure Newton's third law doesn't cause the gun to smash into a wall.",
        "authorsnotes": "Another Commando 2 ripoff. Think of it as Serious Sam's cannon, but with rockets.",
        "designnotes": ""
    },
    {
        "name": "Skulltag",
        "fullname": "",
        "ammo": "Rockets x2",
        "category": "Launcher",
        "primary" : "Skull drill",
        "secondary" : "N/A",
        "notes" : "Tougher demons require multiple drills to mind-control.",
        "superior" : "Enemy max health increases blast damage and radius.",
        "durability": true,
        "description": "An unconventional weapon taking advantage of the chaotic nature of hell's armies. It fires a single drill-shaped projectiles than homes in on a demon's head, piercing its brain and crudely controlling it via electric pulses. The intent is to make the tagged demon retreat back to its brethren, at which point the projectile detonates a high-explosive charge.",
        "authorsnotes": "The Cerebral Bore from Turok. The mind-control gimmick comes from the Armadillo secondary fire in Xionic Madness.",
        "designnotes": "Made to look like the XM-345 Skull Drill, Thing Thing 4's interpretation of the Cerebral Bore."
    },
    
    {
        "name": "Plasma Rifle",
        "fullname": "",
        "ammo": "Cells",
        "category": "Special",
        "primary" : "Plasma shots",
        "secondary" : "N/A",
        "notes" : "Small cooldowns after firing.",
        "superior" : "No cooldown and homing projectiles",
        "durability": false,
        "description": "Balls of superheated molecular soup straight out of the tap. Technically not a rifle, as plasma is a bit too amorphous to take advantage of barrel rifling, but lethality doesn't care about technicality.",
        "authorsnotes": "",
        "designnotes": "Didn't look too far for this one."
    },
    {
        "name": "Laser Cannon",
        "fullname": "",
        "ammo": "Cells",
        "category": "Special",
        "primary" : "Laser beam",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Laser charges enemies. Killing a charged enemy causes an explosion.",
        "durability": false,
        "description": "What anyone first thinks about when asked to come up with a sci-fi weapon. No spread, no recoil, no loss of effectiveness at range, no bullet casings; if it didn't require so much energy it would be the perfect weapon.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Plasma Railgun",
        "fullname": "",
        "ammo": "Cells x10",
        "category": "Special",
        "primary" : "Railshot",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Increased damage over distance.",
        "durability": false,
        "description": "A bit of a misnomer as there is no actual rail being fired, but uses the same concept of using electromagnetism to rapidly accelerate a concentrated mass of plasma.",
        "authorsnotes": "",
        "designnotes": "The battery is located right under the sight, which slides forwards when it needs to be reloaded. I also found the idea putting a shitty folding stock on an advanced space gun pretty funny."
    },
    {
        "name": "Ricochet Rifle",
        "fullname": "",
        "ammo": "Cells x2",
        "category": "Special",
        "primary" : "Ricoshot",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Bouncing projectiles target enemies.",
        "durability": false,
        "description": "Concentrating plasma into a dense orb has the neat side effect of stabilising it enough to cause it to bounce a couple of times before dispersing. A nightmare for those worried about friendly fire, partially solved by a trajectory predictor connected to your HUD.",
        "authorsnotes": "Not a novel concept, but this particular design was inspired by the one in Endless War 3. Superior is based on the BTSX shotgun in Final Doomer.",
        "designnotes": ""
    },
    {
        "name": "Lightning Gun",
        "fullname": "",
        "ammo": "Cells",
        "category": "Special",
        "primary" : "High voltage",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Lightning spreads to nearby enemies.",
        "durability": false,
        "description": "One more added to the list of natural phenomena weaponised by mankind. This weapon has limited range but makes up for it with how easy it is to use : press the trigger and just let physics do the aiming for you.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Tesla Cannon",
        "fullname": "",
        "ammo": "Cells x10",
        "category": "Special",
        "primary" : "Tesla shot",
        "secondary" : "N/A",
        "notes" : "Requires reloading.",
        "superior" : "Secondary attack fires a low intensity straight zap. Zapping the tesla ball causes explosive results.",
        "durability": false,
        "description": "A weapon concept that was actually produced during the 20th century but faded into obscurity before it saw any widespread use. Fires tesla balls that zaps nearby lifeforms as they go, only stopping upon contact with solid matter. Do not use in the rain.",
        "authorsnotes": "Superior should be obvious to anyone familiar with Unreal.",
        "designnotes": ""
    },
    {
        "name": "Eviscerator",
        "fullname": "",
        "ammo": "Sawbaldes",
        "category": "Special",
        "primary" : "Sawblade launch",
        "secondary" : "N/A",
        "notes" : "Sawblades on solid surfaces can be retrieved, restoring durability.",
        "superior" : "Pierces enemies and bounces against solid surfaces up to 3 times each.",
        "durability": true,
        "description": "An elegant solution to the classic problem \"I want to make demon sausage but getting close and personnal is hazardous to my health\". An integrated metal reshaper can turn contents of toolboxes into makeshift sawblades.",
        "authorsnotes": "The KF2 Eviscerator, minus the actual sawing. Durability here is a stand-in for the ammo reserves, with a little bit of lore to explain why you can repair sawblades into existence.",
        "designnotes": ""
    },
    {
        "name": "Assault Shield",
        "fullname": "",
        "ammo": "Cells",
        "category": "Special",
        "primary" : "Plasma shot",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Blocked projectiles charges the shield. Secondary fire releases the charge into a short-range shockwave.",
        "durability": true,
        "description": "Why bother with a shield if the best demon-killing strategy is shooting at it until it dies? What if you could shoot at it without the fear of eating a fireball back? Sure you could try to clumsily aim your sidearm around a standard shield, but wouldn't it be better if said shield had an integrated plasma cannon?",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Reflector Shield",
        "fullname": "UAC SHY Reflective Shield",
        "ammo": "Cells",
        "category": "Special",
        "primary" : "N/A",
        "secondary" : "N/A",
        "notes" : "Reflecting projectiles consumes cells. Drains durability if out of cells.",
        "superior" : "Reflected projectiles deals x3 damage to demons in the same class as the one who threw it.",
        "durability": true,
        "description": "Nothing says pacifism like letting the demons kill themselves. Proximity sensors, targetting modules, and enough kinetic energy to make a grown man stumble, just the ingredients needed to gaslight a group of fireball lobbers into solving their anger issues amongst themselves.",
        "authorsnotes": "Would that even count for pacifist speedruns?",
        "designnotes": ""
    },
    {
        "name": "Demon Blaster",
        "fullname": "",
        "ammo": "Demon Energy x4",
        "category": "Special",
        "primary" : "Energy blast",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Debuffs the target causing it to take increased damage from all sources.",
        "durability": false,
        "description": "Due to the demons' preference of cybernetic augments over conventional firearms, it was tricky to reverse-engineer their technology into usable weaponry. This weapon enhances the demon's magical abilities in order to shoot explosive balls of pure infernal energy. Fortunately, they have a tendency to drop a bit of energy when dying, and thus fueling further demon killing.",
        "authorsnotes": "",
        "designnotes": "The stock and grip are supposed to look like they were grafted onto the weapon."
    },
    {
        "name": "Hell Repeater",
        "fullname": "",
        "ammo": "Demon Energy",
        "category": "Special",
        "primary" : "Hellshot burst x4",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Causes toxic buildup around the area of impact.",
        "durability": false,
        "description": "4 barrels of rapid-fire delivery of refined hell energy. This is what counts as finesse in the world of demonic armaments.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Acid Slinger",
        "fullname": "",
        "ammo": "Demon Energy x8",
        "category": "Special",
        "primary" : "Acid ball",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Projectiles leaves an acid trail while airborne.",
        "durability": false,
        "description": "Due to demonic energy being a form of magic, it can easily be transmuted into different forms with radically different physical and chemical attributes. By diluting it with water, it becomes a semi-liquid compound that becomes extremely caustic when exposed to air.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Crystalline Needler",
        "fullname": "",
        "ammo": "Demon Energy",
        "category": "Special",
        "primary" : "Crystal needles",
        "secondary" : "Spread shot x10",
        "notes" : "10+ needles in close proximity causes an explosive reaction.",
        "superior" : "Needles react twice as fast.",
        "durability": false,
        "description": "A compact hell-gun condenses energy into crystal needles. The crystals don't have that much punch individually, but they react violently with each other once critical mass is achieved. The internal condenser takes a while to get going, causing a noticeable delay between the first shot and the storm of projectiles that follows.",
        "authorsnotes": "Inspired by the Needler from Halo.",
        "designnotes": ""
    },
    {
        "name": "Infernal Flamethrower",
        "fullname": "",
        "ammo": "Demon Energy",
        "category": "Special",
        "primary" : "Fire (literally)",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Decreased ammo consumption.",
        "durability": false,
        "description": "Most of hell's denizen use fire as their ranged attack of choice, so it only makes sense for a hell-powered weapon to do the same. The produced fire burns very quickly and doesn't stick to surfaces, so concentrated fire should be the prefered method of attack. (pun not intended)",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Gore Gun",
        "fullname": "",
        "ammo": "Blood",
        "category": "Special",
        "primary" : "Gore spread",
        "secondary" : "Gore bomb",
        "notes" : "Charged by dealing damage close to enemies with any weapon.",
        "superior" : "Rapidly charges while standing in pools of blood or near bloodfalls.",
        "durability": false,
        "description": "A sweet little contraption that turns violence into more violence. Collecting blood charges the weapon, which is then infused with hell magic to form solid projectiles or further concentrated to create blood bombs.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Volcanus",
        "fullname": "",
        "ammo": "Demon Energy x25",
        "category": "Special",
        "primary" : "Volcanic shot",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Spreads more projectiles over a larger area.",
        "durability": true,
        "description": "A little hand-held armaggedon. Projectiles crash into the ground and spews fire and volcanic slag everywhere. Scorching the earth has never been so fun.",
        "authorsnotes": "",
        "designnotes": ""
    },
    
    {
        "name": "BFG 9000",
        "fullname": "",
        "ammo": "Cells x40",
        "category": "Superweapon",
        "primary" : "Big Fucking Ball of Doom",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Projectile zaps nearby enemies while airborne.",
        "durability": false,
        "description": "An autologism crafted into a weapon. Fires a massive ball of plasma followed an obscenely damaging burst of residual energy, strong enough to obliterate even the mightiest of adversaries. Oh yes!",
        "authorsnotes": "",
        "designnotes": "I added a bit of M41A pulse rifle to give the silhouette some more definition. Otherwise it's a pretty by-the-books BFG."
    },
    {
        "name": "BFG 2704",
        "fullname": "",
        "ammo": "Cells x40",
        "category": "Superweapon",
        "primary" : "Plasma barrage",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Each projectile fired has a chance to be duplicated.",
        "durability": false,
        "description": "The first succesful attempt at a man-portable superweapon, the 2704 is what led to the serendipitous discovery of bouncy plasma. As the first of its kind, the barrage of plasma shots is somewhat unrefined, causing the power (and thus the color) of each individual shot to be a bit unpredictable.",
        "authorsnotes": "For those unaware, that's how the BFG was originally intended to work. Coming up with an explanation for the christmas balls made for a fun gimmick.",
        "designnotes": ""
    },
    {
        "name": "BFG 10000",
        "fullname": "",
        "ammo": "Cells x5",
        "category": "Superweapon",
        "primary" : "Auto-fire",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "No more wind-up required.",
        "durability": false,
        "description": "As good as the 9000 model is, it has a noticeable skill requirement to use effectively. The 10k remedies this issue by being much more straightforward with a rapid-fire salvo high-intensity plasma.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Tele-frag",
        "fullname": "",
        "ammo": "Cells x50",
        "category": "Superweapon",
        "primary" : "Instant plasma delivery",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Overkill damage causes an explosion proportional to potential damage lost.",
        "durability": false,
        "description": "Ever wanted to weaponise teleportation, but don't want to go through the trouble of setting up teleporter pads? With this masterpiece of engineering, you can now teleport highly unstable plasma right into the demons' guts. Ludicrous gibs!",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Galaxy Burst",
        "fullname": "",
        "ammo": "Cells x10",
        "category": "Superweapon",
        "primary" : "Shooting star",
        "secondary" : "N/A",
        "notes" : "Projectile creates a cosmic star on impact. Shooting projectiles at the star increases its damage and range, up to 5 times.",
        "superior" : "Star also shoots star-shaped projectiles in a horizontal circular pattern. Higher intensity stars shoot more projectiles.",
        "durability": false,
        "description": "The unmatched power of the sun into your tiny mortal hands. The intensity of the fired cataclysm mimics the different life stages of this kind of celestial body : star, supergiant, supernova, black hole and quasar. Fortunately they are nowhere near as close as threatening to our galaxy as the real deal would be.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Disintegrator",
        "fullname": "",
        "ammo": "Cells x??",
        "category": "Superweapon",
        "primary" : "Insta-kill",
        "secondary" : "N/A",
        "notes" : "Ammo cost depends on the health of the target. Doesn't fire when ammo is insufficient.",
        "superior" : "Targets under a certain health threshold require no ammo.",
        "durability": false,
        "description": "The final solution to problem you don't want to spend the time dealing with. Sluggish and ammo-inefficient compared to other superweapons, but it makes for it in raw \"fuck outta here\" potential.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "NUKE",
        "fullname": "",
        "ammo": "Rockets x40",
        "category": "Superweapon",
        "primary" : "Atomic Purification",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "No self-damage. Go nuts.",
        "durability": false,
        "description": "No need for a lengthy explanation. It's a portable nuke launcher, what else is there to say.",
        "authorsnotes": "I don't know what NUKE is an acronym for and honestly I don't really care.",
        "designnotes": ""
    },
    {
        "name": "Mechanised Arm Cannon",
        "fullname": "",
        "ammo": "Bullets | Shells | Rockets | Cells",
        "category": "Superweapon",
        "primary" : "All at once",
        "secondary" : "One at a time",
        "notes" : "Reload cycles through weapons",
        "superior" : "Rate of fire increases with continued fire. Cycling weapons provides a temporary fire rate boost.",
        "durability": false,
        "description": "In an attempt to get the most firepower possible, a mechanical arm was developped with weapons for all commonly used weapon types. A machine-gun, shotgun, rocket launcher and plasma beam caster can all be fired using the user's fingers, individually to fit the situation, or in most cases all at once.",
        "authorsnotes": "Yet another Commando 2 rip, with double the guns.",
        "designnotes": ""
    },
    {
        "name": "Megalaser",
        "fullname": "",
        "ammo": "Cells",
        "category": "Superweapon",
        "primary" : "Megalaser",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Destroys enemy projectiles.",
        "durability": true,
        "description": "Originally a tank-mounted weapon for destroying aircraft, this nuclear-powered tool of destruction is strong enough to turn even the hardest of metals into slag, which has the unfortunate drawback of severly limiting how long you can have fun before frying all of its components, but oh boy do you have fun.",
        "authorsnotes": "Inspired by the powerup of the same name in Heavy Weapon. My favorite superweapon ever, mostly for the sound it makes.",
        "designnotes": ""
    },

    {
        "name": "Hand Grenade",
        "fullname": "",
        "ammo": "Grenades",
        "category": "Throwable",
        "primary" : "Throw",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Spreads fragments when exploding.",
        "durability": false,
        "description": "The prefered way of greeting a group of hellspawn, grenades are typically used to clear rooms without having to confront the danger directly, but are also an lightweight alternative to dedicated launchers. Articulated shoulder cannons also exist for those with not enough arms to hold their gun and throw grenades at the same time.",
        "authorsnotes": "",
        "designnotes": "It has a pin and looks like a grenade."
    },
    {
        "name": "Homing Grenade",
        "fullname": "",
        "ammo": "Grenades",
        "category": "Throwable",
        "primary" : "Throw",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Fires bullets towards the targetted enemy.",
        "durability": false,
        "description": "An impact grenade flying towards the enemy with all the grace of a screeching flaming skull. The integrated electronics and fuel required for flight takes away valuable gunpowder space, reducing its effectiveness.",
        "authorsnotes": "Inspired by the Homing grenade modifier from Borderlands 2, and the superior is based on the Deliverance shotgun.",
        "designnotes": ""
    },
    {
        "name": "Spider Grenade",
        "fullname": "",
        "ammo": "Grenades",
        "category": "Throwable",
        "primary" : "Throw",
        "secondary" : "Throw with seeking disabled",
        "notes" : "",
        "superior" : "No self-damage. Spawns a swarm of tiny seeking spiders upon exploding.",
        "durability": false,
        "description": "A devious little devices that scuttles towards its target before exploding it up high in the air. AI can be disabled to give the user more control over the location of the explosion, for example to be able to access high places without the aid of unholy devil magic.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Cryo Grenade",
        "fullname": "",
        "ammo": "Grenades",
        "category": "Throwable",
        "primary" : "Throw",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Increased freeze duration.",
        "durability": false,
        "description": "Bring the cold straight to hell. Flash-freezes a sizeable area, causing demons to have trouble moving around as their bodies fail to adapt to the sudden temperature drop. As an added bonus, frozen flesh breaks apart much more easily, causing tougher demons to fall more quickly to concentrated fire.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Throwing Knife-Bombs",
        "fullname": "",
        "ammo": "Grenades",
        "category": "Throwable",
        "primary" : "Throw",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Knives become proximity mines when hitting a solid surface.",
        "durability": false,
        "description": "Combines the speed and accuracy of a throwing knife and the punch of a grenade. Close combat with these is not recommended if one prefers keeping 2 functioning arms.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Tesla Field Generator",
        "fullname": "",
        "ammo": "Grenades",
        "category": "Throwable",
        "primary" : "Throw",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : "Enemies in the field stop moving.",
        "durability": false,
        "description": "A single explosive is sometimes not enough to hold its own against swarms of angry monsters, but a long-lasting field of particularly excited electrons will do the trick just fine. Keep away from electronical devices.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Rolling Thunder",
        "fullname": "",
        "ammo": "Grenades x3",
        "category": "Throwable",
        "primary" : "Throw",
        "secondary" : "N/A",
        "notes" : "Causes 5 explosions in a straight line away from the point of impact.",
        "superior" : "Third explosion creates an additional 4, perpendicular to the trajectory, resulting in a + shape.",
        "durability": false,
        "description": "A surgical strike in a ball. Please refrain from trying to bounce these off walls, it was already hard enough to get them to explode in the correct direction.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Mini Turret",
        "fullname": "",
        "ammo": "Grenades",
        "category": "Throwable",
        "primary" : "Throw",
        "secondary" : "N/A",
        "notes" : "Fires a machine-gun at targets within range. Enemies can target and destroy it prematurely. Destroys itself when out of ammo.",
        "superior" : "Indestructible. Enemies immediately target the turret upon being shot.",
        "durability": false,
        "description": "A cute little gun to throw at your problems. Take care of your turrets and they'll take care of you back. Sacrificing them in order to save yourself is fine too, they're dumb robots they don't have feelings." ,
        "authorsnotes": "",
        "designnotes": ""
    },

    {
        "name": "Unmaker",
        "fullname": "",
        "ammo": "Demon Energy x3",
        "category": "Artifact",
        "primary" : "Energy shots x3",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : [
            "Fires 5 shots horizontally. Ammo cost rises to 5.",
            "Fires 7 shots horizontally. Ammo cost rises to 7.",
            "Fires 9 shots horizontally. Ammo cost rises to 9."
        ],
        "durability": false,
        "description": "Hidden within the deepest darkest corners of hell, this weapon looks demonic yet no demon has been seen using it. Given how strong it is in human hands, maybe it's for the better.",
        "authorsnotes": "",
        "designnotes": ""
    },
    {
        "name": "Scythe",
        "fullname": "",
        "ammo": "N/A",
        "category": "Artifact",
        "primary" : "Horizontal slash",
        "secondary" : "N/A",
        "notes" : "",
        "superior" : [
            "Secondary attack creates a horizontal spread of fireballs. Costs 5 Demon Energy.",
            "Extracts demon energy on primary attack kills. Amount is based on enemy max health.",
            "Secondary attack also creates a spread of homing hellfire. Ammo cost rises to 10."],
        "durability": false,
        "description": "Harbinger of the apocalypse. Unavoidable finality. Impartial judgement. Dancing in an unending back and forth against the mortal masses like crops at harvest time. Go, and destroy some worlds.",
        "authorsnotes": "A tribute to Scythe 1 and 2 (the megawads). Level 1 and 3 are based on the Afrit's attacks. And yes that one part of the description is taken straight from the dean.",
        "designnotes": ""
    }
]