export default [
    {"slot": 1, "name": "Chainsaw", "ammo": "None", "tags": ["No Augments"], "superior": "None"},
    {"slot": 1, "name": "Truck Wheel Launcher", "ammo": "None", "tags": ["Durability", "Secret"], "superior": "None"},

    {"slot": 2, "name": "Pistol", "ammo": "Bullets", "tags": [], "superior": "Fires explosive projectiles (4 ammo per shot)"},
    {"slot": 2, "name": "Security Pistol", "ammo": "Bullets", "tags": ["Gunlocker"], "superior": "Alt-fire now stuns groups and direct hits can stun bosses"},
    {"slot": 2, "name": "Flare Gun", "ammo": "Rockets", "tags": ["Gunlocker"], "superior": "Magazine size increases to 5. Alt-fire fires all flares in a horizontal spread"},
    {"slot": 2, "name": "Laser Rifle", "ammo": "Cells", "tags": [], "superior": "Full-auto and piercing beams (3 ammo per shot)"},
    {"slot": 2, "name": "Maximum", "ammo": "Bullets", "tags": ["Gunlocker", "Arcane"], "superior": "Alt-fire shoots a gigantic supersonic bullet (100 ammo per shot)"},

    {"slot": 3, "name": "Shotgun", "ammo": "Shells", "tags": [], "superior": "Dragon's breath rounds"},
    {"slot": 3, "name": "Jagdpanzer", "ammo": "Shells", "tags": ["Magazine", "Gunlocker"], "superior": "Fires an extra high-damage piercing shot"},
    {"slot": 3, "name": "Slug Shotgun", "ammo": "Shells", "tags": [], "superior": "Extra knockback to enemies"},
    {"slot": 3, "name": "Super Shotgun", "ammo": "Shells", "tags": [], "superior": "Extra short-range pellets"},
    {"slot": 3, "name": "Shrapnel Shotgun", "ammo": "Shells", "tags": [], "superior": "Projectiles are no longer affected by gravity"},
    {"slot": 3, "name": "Auto Shotgun", "ammo": "Shells", "tags": ["Magazine"], "superior": "No longer needs to reload"},
    {"slot": 3, "name": "Riot Shotgun", "ammo": "Shells", "tags": ["Magazine"], "superior": "Stabilised spread"},
    {"slot": 3, "name": "Quad Shotgun", "ammo": "Shells", "tags": [], "superior": "Fires a strong shockwave and increased self-knockback"},
    {"slot": 3, "name": "Raiden Electron Shotgun", "ammo": "Shells", "tags": ["Arcane", "Magazine"], "superior": "Shoots a large lightning bolt during alt-fire"},
    {"slot": 3, "name": "Streetsweeper", "ammo": "Shells", "tags": ["Durability"], "superior": "None"},

    {"slot": 4, "name": "Assault Rifle", "ammo": "Bullets", "tags": [], "superior": "Fires 2 bullets at once with reduced damage"},
    {"slot": 4, "name": "Burst Rifle", "ammo": "Bullets", "tags": [], "superior": "Semi-auto with rapid bursts"},
    {"slot": 4, "name": "Nailgun", "ammo": "Bullets", "tags": [], "superior": "Nails deal more damage for every enemy pierced"},
    {"slot": 4, "name": "Atom Blaster", "ammo": "Bullets", "tags": [], "superior": "Projectiles duplicate when bouncing"},
    {"slot": 4, "name": "Light Machinegun", "ammo": "Bullets", "tags": ["Magazine"], "superior": "Faster fire rate, increased mag size, decreased accuracy"},
    {"slot": 4, "name": "Vengeful Blade", "ammo": "Bullets", "tags": ["Gunlocker"], "superior": "Consumes 1 less ammo per shot"},
    {"slot": 4, "name": "Firestorm", "ammo": "Bullets", "tags": ["Durability"], "superior": "None"},

    {"slot": 5, "name": "Rocket Launcher", "ammo": "Rockets", "tags": [], "superior": "Laser-guided rockets"},
    {"slot": 5, "name": "Direct Hit", "ammo": "Rockets", "tags": [], "superior": "Rocket damage increases while traveling"},
    {"slot": 5, "name": "Grenade Launcher", "ammo": "Rockets", "tags": [], "superior": "Grenades deal more damage and explode on impact"},
    {"slot": 5, "name": "Napalm Bomber", "ammo": "Rockets", "tags": ["No Flame"], "superior": "Spreads more fire"},
    {"slot": 5, "name": "Stickybomb Launcher", "ammo": "Rockets", "tags": [], "superior": "Grenades explode multiple times"},
    {"slot": 5, "name": "Dual Missile Launcher", "ammo": "Rockets", "tags": [], "superior": "Accelerates and homes in more aggressively"},
    {"slot": 5, "name": "Dark Blaster", "ammo": "Demon", "tags": [], "superior": "Shoots a shockwave when cooling down and consumes 1 less ammo per shot"},
    {"slot": 5, "name": "HE Rocket Launcher", "ammo": "Rockets", "tags": [], "superior": "Magazine size increases to 3"},
    {"slot": 5, "name": "Flamethrower", "ammo": "Rockets", "tags": ["Magazine"], "superior": "Airblast altfire"},
    {"slot": 5, "name": "Flak Cannon", "ammo": "Rockets", "tags": ["Gunlocker"], "superior": "Primary fire shoots additional explosive tracers. Secondary fire has increased impact damage and spawns more flames"},
    {"slot": 5, "name": "Solarion", "ammo": "Demon", "tags": ["Gunlocker"], "superior": "Beams split into homing balls on impact"},
    {"slot": 5, "name": "Meteorite", "ammo": "Rockets", "tags": ["Durability"], "superior": "None"},
    
    {"slot": 6, "name": "Plasma Rifle", "ammo": "Cells", "tags": [], "superior": "No cooldown"},
    {"slot": 6, "name": "Overcharge Rifle", "ammo": "Cells", "tags": [], "superior": "Charges passively over time (even when holstered)"},
    {"slot": 6, "name": "Railgun", "ammo": "Cells", "tags": ["No Precision"], "superior": "Damage increases over distance"},
    {"slot": 6, "name": "Railbeam", "ammo": "Cells", "tags": ["No Precision"], "superior": "Piercing beam"},
    {"slot": 6, "name": "Plasma Repeater", "ammo": "Cells", "tags": [], "superior": "No longer winds up"},
    {"slot": 6, "name": "Laser Minigun", "ammo": "Cells", "tags": [], "superior": "Spawns a shield when firing"},
    {"slot": 6, "name": "Scourge Rifle", "ammo": "Demon", "tags": ["Magazine"], "superior": "No cooldown and projectiles create poison clouds"},
    {"slot": 6, "name": "Spinfusor", "ammo": "Cells", "tags": ["Magazine"], "superior": "Shoots stabilised bouncing projectiles"},
    {"slot": 6, "name": "Enlightener", "ammo": "Cells", "tags": ["Durability"], "superior": "None"},
    {"slot": 6, "name": "Phase DMR", "ammo": "Cells", "tags": ["Gunlocker"], "superior": "5-shot burst. Shots travel instantly and don't cause any self damage"},
    {"slot": 6, "name": "Silver Buster", "ammo": "Cells", "tags": ["Gunlocker"], "superior": "No longer needs to pump"},
    
    {"slot": 7, "name": "BFG 9000", "ammo": "Cells", "tags": [], "superior": "Projectiles now shoots extra tracers on impact"},
    {"slot": 7, "name": "Gauss Annihilator", "ammo": "Cells", "tags": ["No Precision"], "superior": "No self damage"},
    {"slot": 7, "name": "BFG 10000", "ammo": "Cells", "tags": [], "superior": "Shoots tracers"},
    {"slot": 7, "name": "Perforator", "ammo": "Bullets", "tags": [], "superior": "Fires 5 additional piercing shots on first barrage"},
    {"slot": 7, "name": "Hakkero Magicannon", "ammo": "Cells", "tags": ["Arcane"], "superior": "Fires additional star projectiles"},
    {"slot": 7, "name": "Heliacal Arc", "ammo": "Demon", "tags": ["Durability"], "superior": "None"},
    
    {"slot": 8, "name": "Sacrosanct Aeonstave", "ammo": "Chaos", "tags": ["No Augments"], "superior": "None"},
    {"slot": 8, "name": "Convergence", "ammo": "Demon", "tags": ["No Augments"], "superior": "None"}
]